sonar.projectKey=FMAT-Restaurant_Menu-Frontend
sonar.organization=fmat-restaurant
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.test.ts,src/**/*.test.tsx,src/test-setup.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
